### ISSUE TITLE
[Feat] 팜클럽 초기 UI 구현

### ISSUE THREAD

**Issue by arinming** [Mojacknong/Mojacknong_Android#155]
## ✏️ Description
팜클럽 바텀 네비를 눌렀을 때의 초기 상태를 구현합니다

## To-Do List
- [x] 팜클럽 정보
- [x] 탭바
- [x] Step 상세
- [x] 도움말
- [x] 일기

## ETC
아 드디어 팜클럽!

**Comment by geonheey** [comment]
홈 화면 너무 고생 많았습니다 🥹
